// <auto-generated />
using System;
using MarketPlace_Orders.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketPlace_Orders.Migrations
{
    [DbContext(typeof(MarketPlaceContext))]
    [Migration("20220911091000_AddedFinalData")]
    partial class AddedFinalData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.7.22376.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarketPlace_Orders.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("779538e2-221b-459e-9362-c773d154bf4e"),
                            Location = "Pune",
                            Name = "Darshil Parmar"
                        },
                        new
                        {
                            Id = new Guid("c6cefcb6-c330-4944-a8e6-5eb8bf92fc53"),
                            Location = "Kolkata",
                            Name = "Darshil Maheriya"
                        },
                        new
                        {
                            Id = new Guid("8875f86a-d830-4934-a7d7-8fc2dff8b318"),
                            Location = "Goa",
                            Name = "Darshil Virani"
                        },
                        new
                        {
                            Id = new Guid("ea6e3c47-ceb3-49f7-abce-510185d00420"),
                            Location = "Mumbai",
                            Name = "Aelish Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("02d10ff5-802e-4595-b9de-d9f597b3f8be"),
                            Location = "Gandhinagar",
                            Name = "Darshil Maheriya"
                        },
                        new
                        {
                            Id = new Guid("127c77f9-8836-4ef9-adf0-4761b4e03acb"),
                            Location = "Pune",
                            Name = "Vishesh Agrawal"
                        },
                        new
                        {
                            Id = new Guid("df1e9f15-c888-4ec7-acec-a6ed10fc16b4"),
                            Location = "Gandhinagar",
                            Name = "Harsh Virani"
                        },
                        new
                        {
                            Id = new Guid("cd871242-5e86-4470-888f-43a321271fc9"),
                            Location = "Bangalore",
                            Name = "Harsh Maheriya"
                        },
                        new
                        {
                            Id = new Guid("83bbe6bd-da6e-4246-99a0-0d92ad31127b"),
                            Location = "Ahmedabad",
                            Name = "Vishesh Parmar"
                        },
                        new
                        {
                            Id = new Guid("a57a9bb5-ad3d-406c-a1fb-9f4614619d6e"),
                            Location = "Mumbai",
                            Name = "Tejas Virani"
                        },
                        new
                        {
                            Id = new Guid("3736aeef-6350-4f1f-a947-e640f4baa2b4"),
                            Location = "Kerala",
                            Name = "Darshil Virani"
                        },
                        new
                        {
                            Id = new Guid("a220605a-2505-4876-aa0e-b03b01b3bfe0"),
                            Location = "Ahmedabad",
                            Name = "Tejas Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("e6937e55-471a-4af0-a950-6b6f85301ad8"),
                            Location = "Kerala",
                            Name = "Tejas Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("524ffef3-e0d0-4291-ac76-729874d19a27"),
                            Location = "Mumbai",
                            Name = "Darshil Agrawal"
                        },
                        new
                        {
                            Id = new Guid("b0d54b53-968b-49e2-ada2-52aab6dee7f4"),
                            Location = "Mumbai",
                            Name = "Darshil Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("542873a2-29c5-47e3-8793-7929c7605b78"),
                            Location = "Chennai",
                            Name = "Harsh Parmar"
                        },
                        new
                        {
                            Id = new Guid("15bb5efc-f36a-4e34-b132-5f0aa8be9c95"),
                            Location = "Gandhinagar",
                            Name = "Tejas Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("21255588-9d9e-4529-99f6-604908b40ae7"),
                            Location = "Gandhinagar",
                            Name = "Harsh Virani"
                        },
                        new
                        {
                            Id = new Guid("69de1030-d3bd-4630-adfa-4ad52395f538"),
                            Location = "Kerala",
                            Name = "Vishesh Virani"
                        },
                        new
                        {
                            Id = new Guid("b96748f4-30ce-491d-9c1e-34f7416ec983"),
                            Location = "Kerala",
                            Name = "Vishesh Virani"
                        },
                        new
                        {
                            Id = new Guid("0d75100f-9d2a-47d9-bb7d-0139a6ede622"),
                            Location = "Chennai",
                            Name = "Vishesh Virani"
                        },
                        new
                        {
                            Id = new Guid("4ebc1241-84f7-4335-b779-b6887bd5d44d"),
                            Location = "Kolkata",
                            Name = "Kush Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("6f73de6c-ae34-4f2e-bfc2-70ede09c1a75"),
                            Location = "Kerala",
                            Name = "Harsh Parmar"
                        },
                        new
                        {
                            Id = new Guid("28bbe30e-0e49-45b3-966e-f6f20790a167"),
                            Location = "Pune",
                            Name = "Kush Maheriya"
                        },
                        new
                        {
                            Id = new Guid("a42918de-ac15-4096-bc05-8d5a9a12feeb"),
                            Location = "Kerala",
                            Name = "Darshil Maheriya"
                        },
                        new
                        {
                            Id = new Guid("c9e4cf71-1c5c-429d-9c37-8510b75beb3c"),
                            Location = "Gandhinagar",
                            Name = "Harsh Agrawal"
                        },
                        new
                        {
                            Id = new Guid("16f97040-30b5-4e53-85d0-2d24fd1eae8b"),
                            Location = "Pune",
                            Name = "Aelish Agrawal"
                        },
                        new
                        {
                            Id = new Guid("13597617-f48d-45d6-bfd9-88819ad06b53"),
                            Location = "Kolkata",
                            Name = "Kush Virani"
                        },
                        new
                        {
                            Id = new Guid("9e1f9ae8-7af5-4a6c-8f13-d294f314546c"),
                            Location = "Ahmedabad",
                            Name = "Tejas Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("033279f0-009f-4bb5-ab11-458a196eef05"),
                            Location = "Mumbai",
                            Name = "Kush Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("4aa3f273-128f-4e93-a24a-60e9ab4c568a"),
                            Location = "Delhi",
                            Name = "Tejas Agrawal"
                        },
                        new
                        {
                            Id = new Guid("c68eac15-b2fb-42a0-ab20-f31195f44bd2"),
                            Location = "Ahmedabad",
                            Name = "Aelish Parmar"
                        },
                        new
                        {
                            Id = new Guid("2491968a-c0d5-4fa7-b8f2-7a30b3c6fe58"),
                            Location = "Pune",
                            Name = "Harsh Agrawal"
                        },
                        new
                        {
                            Id = new Guid("d195af26-763d-413c-a12b-4f25f80b118f"),
                            Location = "Kolkata",
                            Name = "Tejas Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("dbabbf67-4111-4d20-b494-6e62a8b8d26a"),
                            Location = "Mumbai",
                            Name = "Harsh Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("fdeacda7-0ac9-40d0-9bae-707123dfdf6e"),
                            Location = "Ahmedabad",
                            Name = "Darshil Virani"
                        },
                        new
                        {
                            Id = new Guid("6781b274-1e2c-481e-8529-e192fb2b799f"),
                            Location = "Ahmedabad",
                            Name = "Kush Agrawal"
                        },
                        new
                        {
                            Id = new Guid("941ce9ee-ff67-4339-8231-101c61c0c2e8"),
                            Location = "Bangalore",
                            Name = "Kush Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("a6227165-ef8c-4c49-87a9-367a4e0ba4e7"),
                            Location = "Bangalore",
                            Name = "Darshil Maheriya"
                        },
                        new
                        {
                            Id = new Guid("a3fee42d-89ea-4e71-aae1-81e52e70903c"),
                            Location = "Delhi",
                            Name = "Harsh Maheriya"
                        },
                        new
                        {
                            Id = new Guid("5c8c529c-4896-4132-9a13-48dbbee650a6"),
                            Location = "Ahmedabad",
                            Name = "Kush Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("a777afdb-6aff-4b41-9177-8ce9acf2ae54"),
                            Location = "Goa",
                            Name = "Vishesh Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("b4267c6c-8e89-454a-9402-4cb0d46372b2"),
                            Location = "Mumbai",
                            Name = "Aelish Virani"
                        },
                        new
                        {
                            Id = new Guid("10d48611-681f-4d26-9baf-c985c775bab8"),
                            Location = "Delhi",
                            Name = "Tejas Virani"
                        },
                        new
                        {
                            Id = new Guid("592d98ce-942e-45f8-bb3e-733312d2de5c"),
                            Location = "Delhi",
                            Name = "Aelish Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("e2bf4ef0-e43f-4f8f-ae0a-17e3c54e9264"),
                            Location = "Kerala",
                            Name = "Tejas Agrawal"
                        },
                        new
                        {
                            Id = new Guid("f1c591e3-5b65-456c-8a68-49655a583e0e"),
                            Location = "Kerala",
                            Name = "Vishesh Maheriya"
                        },
                        new
                        {
                            Id = new Guid("3e448bcb-8f4c-430f-8d4c-65c937af51c4"),
                            Location = "Kerala",
                            Name = "Vishesh Agrawal"
                        },
                        new
                        {
                            Id = new Guid("d2fa988a-d82b-4bfe-b047-8c33e7a2d34a"),
                            Location = "Delhi",
                            Name = "Harsh Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("e80e9713-7483-416a-960e-d9470542126a"),
                            Location = "Kerala",
                            Name = "Harsh Virani"
                        });
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.DeliveryBoy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryBoys");
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.MarketPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MarketPlaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41424202-6d92-4ea3-8205-bebeb873f1fd"),
                            Name = "Zomato"
                        },
                        new
                        {
                            Id = new Guid("6d9c4ef6-0217-4445-9567-346f480828d1"),
                            Name = "Swiggy"
                        },
                        new
                        {
                            Id = new Guid("674e04bf-8533-4b5f-b9f8-12bb45db4589"),
                            Name = "Uber Eats"
                        },
                        new
                        {
                            Id = new Guid("0b271f6b-575d-4e9c-8e18-75364dda57f7"),
                            Name = "Food Panda"
                        });
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.Orders", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutletName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBill")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<Guid>("RestaurantId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId1");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("828d3869-45eb-4124-9bbe-a5b4d62dd29d"),
                            Name = "KFC"
                        },
                        new
                        {
                            Id = new Guid("7625e355-e88a-435a-bbaa-63de273a0c3a"),
                            Name = "Dominos"
                        },
                        new
                        {
                            Id = new Guid("cf58c79a-ab87-4e89-9560-2165610f46cc"),
                            Name = "Pizza Hut"
                        },
                        new
                        {
                            Id = new Guid("02fd65a1-6d1a-4c66-a589-7eb0cc357080"),
                            Name = "City Point"
                        },
                        new
                        {
                            Id = new Guid("53903fd0-850f-41e4-a8dd-64a48671c208"),
                            Name = "Farki "
                        });
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.Product", b =>
                {
                    b.HasOne("MarketPlace_Orders.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });
#pragma warning restore 612, 618
        }
    }
}
