// <auto-generated />
using System;
using MarketPlace_Orders.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketPlace_Orders.Migrations
{
    [DbContext(typeof(MarketPlaceContext))]
    [Migration("20220911085933_ChangedTheName")]
    partial class ChangedTheName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.7.22376.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarketPlace_Orders.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3fb56f4b-c575-42f5-ad52-e8f67f684fc0"),
                            Location = "Ahmedabad",
                            Name = "Aelish Parmar"
                        },
                        new
                        {
                            Id = new Guid("cb507826-46b1-4940-a057-8bd296f478c9"),
                            Location = "Chennai",
                            Name = "Vishesh Kushwah"
                        },
                        new
                        {
                            Id = new Guid("69442587-fa39-4d60-94ef-65e1fc6db71c"),
                            Location = "Mumbai",
                            Name = "Naisarg Maheriya"
                        },
                        new
                        {
                            Id = new Guid("8898bcf2-f256-4bda-8d87-5cd626e350ef"),
                            Location = "Delhi",
                            Name = "Raj Agrawal"
                        },
                        new
                        {
                            Id = new Guid("22a895cc-0049-4f57-91ea-c35b6a29d94e"),
                            Location = "Ahmedabad",
                            Name = "Vishesh Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("f71e3b2f-f072-435d-b90e-2b7f370db5cf"),
                            Location = "Ahmedabad",
                            Name = "Darshil Parmar"
                        },
                        new
                        {
                            Id = new Guid("dae3a92f-9736-4b92-bd7d-fa92c053f04e"),
                            Location = "Kerala",
                            Name = "Darshil Rathod"
                        },
                        new
                        {
                            Id = new Guid("91ed6d06-d2b5-4d30-84c6-1620989e6783"),
                            Location = "Delhi",
                            Name = "Harsh Rathod"
                        },
                        new
                        {
                            Id = new Guid("897eed88-ed4a-4e23-8c38-c22b25dc17db"),
                            Location = "Kerala",
                            Name = "Ramesh Sharma"
                        },
                        new
                        {
                            Id = new Guid("19e179df-0ccf-4c41-8d13-30590b3c7e61"),
                            Location = "Delhi",
                            Name = "Kush Kushwah"
                        },
                        new
                        {
                            Id = new Guid("6a77c9e1-80cb-4e18-a999-507d7816fd84"),
                            Location = "Gandhinagar",
                            Name = "Raj Verma"
                        },
                        new
                        {
                            Id = new Guid("4502af7b-002e-4fb8-a329-5d9d8804183e"),
                            Location = "Kolkata",
                            Name = "Amit Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("201a1e56-142c-4060-b2c7-6df37917c8a4"),
                            Location = "Chennai",
                            Name = "Ramesh Rathod"
                        },
                        new
                        {
                            Id = new Guid("59dabe54-cec6-4b06-9c99-4921b6811813"),
                            Location = "Bangalore",
                            Name = "Harsh Sharma"
                        },
                        new
                        {
                            Id = new Guid("c59d07f8-f2d9-4567-af0c-74ae2169b40a"),
                            Location = "Ahmedabad",
                            Name = "Amit Virani"
                        },
                        new
                        {
                            Id = new Guid("b2d3caea-829a-465a-823d-141fbeccb042"),
                            Location = "Chennai",
                            Name = "Darshil Sharma"
                        },
                        new
                        {
                            Id = new Guid("b4d5a717-7a8e-48bf-a8e6-7ddf193ec427"),
                            Location = "Bangalore",
                            Name = "Kush Rathod"
                        },
                        new
                        {
                            Id = new Guid("8bab272b-f693-437c-91e0-1dfd1ab7b2fb"),
                            Location = "Chennai",
                            Name = "Aelish Agrawal"
                        },
                        new
                        {
                            Id = new Guid("f9cddba0-e60c-4c34-b9cc-bbb24ee2ef74"),
                            Location = "Chennai",
                            Name = "Darshil Maheriya"
                        },
                        new
                        {
                            Id = new Guid("f37bcb4e-de67-464b-82b1-912056daa32a"),
                            Location = "Pune",
                            Name = "Raj Kushwah"
                        },
                        new
                        {
                            Id = new Guid("dc2004cb-3531-4eff-9ac0-4ee3dc03726a"),
                            Location = "Kerala",
                            Name = "Naisarg Virani"
                        },
                        new
                        {
                            Id = new Guid("50da3f81-2745-4151-a2fe-9f5453e7f1f9"),
                            Location = "Delhi",
                            Name = "Naisarg Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("360d18ab-a28b-4606-a665-13b9ae1329ba"),
                            Location = "Goa",
                            Name = "Amit Sharma"
                        },
                        new
                        {
                            Id = new Guid("8019de8a-b207-4d92-aec2-b6e90c528e7c"),
                            Location = "Delhi",
                            Name = "Ramesh Parmar"
                        },
                        new
                        {
                            Id = new Guid("b26d46a4-0320-4fef-bc23-df19258953a6"),
                            Location = "Pune",
                            Name = "Aelish Verma"
                        },
                        new
                        {
                            Id = new Guid("805f5fa4-608f-4e16-a4b4-d220d04f1d5b"),
                            Location = "Mumbai",
                            Name = "Naisarg Kushwah"
                        },
                        new
                        {
                            Id = new Guid("f288c7fd-ac77-46ad-9b4a-86c946f3b613"),
                            Location = "Chennai",
                            Name = "Kush Agrawal"
                        },
                        new
                        {
                            Id = new Guid("d2240e73-42b0-412c-89f2-1b5d55781431"),
                            Location = "Gandhinagar",
                            Name = "Amit Agrawal"
                        },
                        new
                        {
                            Id = new Guid("6cb4015a-811c-46b3-b9b3-0ae37e9295b6"),
                            Location = "Delhi",
                            Name = "Harsh Virani"
                        },
                        new
                        {
                            Id = new Guid("d6672141-ec28-4aa2-ab32-48db271e88ad"),
                            Location = "Kerala",
                            Name = "Ramesh Maheriya"
                        },
                        new
                        {
                            Id = new Guid("73691056-0073-4cef-9721-01676e29444c"),
                            Location = "Gandhinagar",
                            Name = "Raj Verma"
                        },
                        new
                        {
                            Id = new Guid("0c2c78b8-499a-4e01-88dc-ea46fb210de0"),
                            Location = "Gandhinagar",
                            Name = "Tejas Verma"
                        },
                        new
                        {
                            Id = new Guid("8fdac3e8-7023-4cad-951f-046a0ac864e9"),
                            Location = "Kolkata",
                            Name = "Naisarg Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("a56fc0c4-c7fc-428c-b36b-fd68e793cf6b"),
                            Location = "Kolkata",
                            Name = "Kush Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("ff342ec2-6acb-4768-a5db-802225748d26"),
                            Location = "Kerala",
                            Name = "Harsh Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("95f6c96b-2202-453f-ae48-aea42fd28774"),
                            Location = "Ahmedabad",
                            Name = "Aelish Parmar"
                        },
                        new
                        {
                            Id = new Guid("0b6dc3aa-ca7a-4e0c-9d5a-acff08ac42d5"),
                            Location = "Chennai",
                            Name = "Aelish Virani"
                        },
                        new
                        {
                            Id = new Guid("8380f93d-0411-41a7-88e2-4390bc76f1ab"),
                            Location = "Kerala",
                            Name = "Aelish Parmar"
                        },
                        new
                        {
                            Id = new Guid("e66f05b3-a711-4851-b161-dffa928fa5ed"),
                            Location = "Kerala",
                            Name = "Kush Kushwah"
                        },
                        new
                        {
                            Id = new Guid("82d86143-23b7-4379-8ff5-aada60a33496"),
                            Location = "Gandhinagar",
                            Name = "Naisarg Sharma"
                        },
                        new
                        {
                            Id = new Guid("66393eb8-919b-40b3-a3e1-04641bcb70e9"),
                            Location = "Goa",
                            Name = "Amit Verma"
                        },
                        new
                        {
                            Id = new Guid("4af980ca-c6d0-4ee1-adc7-5a6323c8a1ec"),
                            Location = "Kolkata",
                            Name = "Harsh Rathod"
                        },
                        new
                        {
                            Id = new Guid("cb1fa749-5054-4769-84ef-dd6354c3012d"),
                            Location = "Bangalore",
                            Name = "Harsh Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("6bead8b0-6156-4159-b32f-10c39c049531"),
                            Location = "Kolkata",
                            Name = "Amit Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("cdd56eff-3020-40ac-8fd7-f9d2044ea39e"),
                            Location = "Mumbai",
                            Name = "Tejas Virani"
                        },
                        new
                        {
                            Id = new Guid("f914c7ee-61ec-4342-9b7b-fb5e1b6f4069"),
                            Location = "Gandhinagar",
                            Name = "Ramesh Sharma"
                        },
                        new
                        {
                            Id = new Guid("0242de8d-d336-4ba2-9eba-4acbcd6cca87"),
                            Location = "Delhi",
                            Name = "Vishesh Rathod"
                        },
                        new
                        {
                            Id = new Guid("59294ed8-c82b-4cfe-befc-67c189adb739"),
                            Location = "Ahmedabad",
                            Name = "Darshil Agrawal"
                        },
                        new
                        {
                            Id = new Guid("cfbea068-d077-422a-b49a-69679f11edfa"),
                            Location = "Mumbai",
                            Name = "Tejas Sharma"
                        },
                        new
                        {
                            Id = new Guid("49012979-a33c-42d9-8d89-b28104f1a13b"),
                            Location = "Bangalore",
                            Name = "Kush Sharma"
                        });
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.DeliveryBoy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryBoys");
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.MarketPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MarketPlaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6a3f246d-bb61-4b92-9171-8f3610fd5081"),
                            Name = "Zomato"
                        },
                        new
                        {
                            Id = new Guid("2966b22d-a425-4dbe-a6e6-06e3e4d1f28b"),
                            Name = "Swiggy"
                        },
                        new
                        {
                            Id = new Guid("6c2048f8-d34c-42ef-9721-48dbe55f4db3"),
                            Name = "Uber Eats"
                        },
                        new
                        {
                            Id = new Guid("32c9b55a-8c48-42ec-bf76-0eba6f44cfc4"),
                            Name = "Food Panda"
                        });
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.Orders", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutletName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBill")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<Guid>("RestaurantId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId1");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0092455a-6112-4ba5-9b45-e523653195b3"),
                            Name = "KFC"
                        },
                        new
                        {
                            Id = new Guid("99dba099-88a5-4ca5-8efd-c70f62dd937b"),
                            Name = "Dominos"
                        },
                        new
                        {
                            Id = new Guid("6d4f7560-985e-4f6b-91fd-bb9a25554c45"),
                            Name = "Pizza Hut"
                        },
                        new
                        {
                            Id = new Guid("53a9e872-de54-42b8-81ae-2f4a6ecde0a8"),
                            Name = "City Point"
                        },
                        new
                        {
                            Id = new Guid("61382ee7-21ad-44bd-9de6-5321affcc367"),
                            Name = "Farki "
                        });
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.Product", b =>
                {
                    b.HasOne("MarketPlace_Orders.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });
#pragma warning restore 612, 618
        }
    }
}
