// <auto-generated />
using System;
using MarketPlace_Orders.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketPlace_Orders.Migrations
{
    [DbContext(typeof(MarketPlaceContext))]
    [Migration("20220911085120_Initializing Database")]
    partial class InitializingDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.7.22376.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarketPlace_Orders.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("441f1e58-8f4d-4687-a5ee-1b6107df17c2"),
                            Location = "Gandhinagar",
                            Name = "Kush Agrawal"
                        },
                        new
                        {
                            Id = new Guid("7727843f-4b5e-4bbc-b4ec-09ac52a6bab2"),
                            Location = "Kerala",
                            Name = "Amit Sharma"
                        },
                        new
                        {
                            Id = new Guid("fe427791-a705-4c50-89f7-6694d33a517b"),
                            Location = "Kolkata",
                            Name = "Aelish Parmar"
                        },
                        new
                        {
                            Id = new Guid("43c38acb-8807-4e3f-abcb-c9a3a02f8393"),
                            Location = "Ahmedabad",
                            Name = "Amit Rathod"
                        },
                        new
                        {
                            Id = new Guid("c7723ff6-e3e7-43e5-af49-a15d221cdbae"),
                            Location = "Delhi",
                            Name = "Amit Maheriya"
                        },
                        new
                        {
                            Id = new Guid("77c61e09-cbb9-41b3-a2fb-06b9871e43ed"),
                            Location = "Bangalore",
                            Name = "Raj Parmar"
                        },
                        new
                        {
                            Id = new Guid("98adf68a-e202-40f2-9856-8cbed7f23d42"),
                            Location = "Goa",
                            Name = "Raj Sharma"
                        },
                        new
                        {
                            Id = new Guid("7a18521d-ab30-487c-a488-60d1bc95504a"),
                            Location = "Kolkata",
                            Name = "Amit Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("6186a528-8734-4f5c-b214-1876fe278101"),
                            Location = "Delhi",
                            Name = "Raj Rathod"
                        },
                        new
                        {
                            Id = new Guid("b9273244-ab8f-4df9-acc9-62f3a5754e99"),
                            Location = "Pune",
                            Name = "Ramesh Maheriya"
                        },
                        new
                        {
                            Id = new Guid("260259af-8388-40ae-ba14-e8ffb73d3161"),
                            Location = "Bangalore",
                            Name = "Harsh Agrawal"
                        },
                        new
                        {
                            Id = new Guid("6a8939e7-2a90-4987-878c-87c838ec9241"),
                            Location = "Mumbai",
                            Name = "Harsh Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("ede12711-d7ca-4f1c-a422-b0c916ffd540"),
                            Location = "Kolkata",
                            Name = "Kush Parmar"
                        },
                        new
                        {
                            Id = new Guid("e25c7c80-736b-4a79-8013-9387759a2aa9"),
                            Location = "Kerala",
                            Name = "Naisarg Parmar"
                        },
                        new
                        {
                            Id = new Guid("5611e3e7-fbf2-4ecc-b204-df2d5bbe6511"),
                            Location = "Kerala",
                            Name = "Darshil Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("cc58f45b-dc10-4140-a185-485c1eb0a0c9"),
                            Location = "Pune",
                            Name = "Darshil Virani"
                        },
                        new
                        {
                            Id = new Guid("2281bd58-14ea-4513-a234-291d9268c432"),
                            Location = "Delhi",
                            Name = "Amit Agrawal"
                        },
                        new
                        {
                            Id = new Guid("e5e61414-857b-451a-8ce7-5db96b3042ad"),
                            Location = "Gandhinagar",
                            Name = "Raj Verma"
                        },
                        new
                        {
                            Id = new Guid("c22e8db9-4bd2-418b-9cd4-218531150f3a"),
                            Location = "Mumbai",
                            Name = "Naisarg Rathod"
                        },
                        new
                        {
                            Id = new Guid("27787c3b-b1c3-440c-93b1-606d7cfe87c4"),
                            Location = "Chennai",
                            Name = "Tejas Maheriya"
                        },
                        new
                        {
                            Id = new Guid("c00dffc1-3361-4607-ba36-8014f73558d9"),
                            Location = "Mumbai",
                            Name = "Kush Sharma"
                        },
                        new
                        {
                            Id = new Guid("b95649a5-c5d6-4447-a66c-bbb7aae4e0c2"),
                            Location = "Goa",
                            Name = "Aelish Virani"
                        },
                        new
                        {
                            Id = new Guid("082ffcfc-a8b1-403f-80a1-55210cf3439e"),
                            Location = "Kerala",
                            Name = "Aelish Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("3f33106f-457f-4fe3-811d-2070792bf055"),
                            Location = "Pune",
                            Name = "Ramesh Maheriya"
                        },
                        new
                        {
                            Id = new Guid("e3fd3b4a-d9c8-40d2-bfc8-0dce622f8321"),
                            Location = "Gandhinagar",
                            Name = "Amit Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("7f0c39ae-15a9-47b4-875e-034464ebb119"),
                            Location = "Goa",
                            Name = "Darshil Kushwah"
                        },
                        new
                        {
                            Id = new Guid("063b823b-a98b-4edf-9335-be396ff5dac9"),
                            Location = "Delhi",
                            Name = "Aelish Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("324cac62-479d-4dda-b37a-d773eecc2896"),
                            Location = "Kolkata",
                            Name = "Harsh Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("74d5e580-4216-4bcf-babd-b68dbe04ee8e"),
                            Location = "Bangalore",
                            Name = "Amit Parmar"
                        },
                        new
                        {
                            Id = new Guid("5681e364-92d6-44cc-a2ae-2ea9a681ac90"),
                            Location = "Kerala",
                            Name = "Tejas Virani"
                        },
                        new
                        {
                            Id = new Guid("8322c278-0525-4f6c-834d-0a33a72bf1ff"),
                            Location = "Chennai",
                            Name = "Kush Parmar"
                        },
                        new
                        {
                            Id = new Guid("b1be0163-d57e-4987-9f6e-54679ec0e19d"),
                            Location = "Bangalore",
                            Name = "Harsh Virani"
                        },
                        new
                        {
                            Id = new Guid("ee563e97-36a7-461c-80cf-d51eea8467bd"),
                            Location = "Kerala",
                            Name = "Naisarg Rathod"
                        },
                        new
                        {
                            Id = new Guid("811a2a81-e1d4-4bd8-a32f-166b6b3ce1d5"),
                            Location = "Pune",
                            Name = "Ramesh Agrawal"
                        },
                        new
                        {
                            Id = new Guid("efd80673-98eb-442a-a690-33e6edf7aaab"),
                            Location = "Bangalore",
                            Name = "Kush Sharma"
                        },
                        new
                        {
                            Id = new Guid("42c7ef65-e6a4-44ab-9614-121987f18da2"),
                            Location = "Kerala",
                            Name = "Harsh Virani"
                        },
                        new
                        {
                            Id = new Guid("8691b414-6e05-4414-a460-5260ad110c29"),
                            Location = "Bangalore",
                            Name = "Amit Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("163a2e0b-74aa-4d6e-af58-b5736782daa0"),
                            Location = "Kolkata",
                            Name = "Ramesh Maheriya"
                        },
                        new
                        {
                            Id = new Guid("a289608d-80e0-4165-a1fd-a36970fadbfb"),
                            Location = "Mumbai",
                            Name = "Vishesh Verma"
                        },
                        new
                        {
                            Id = new Guid("968c49f1-ae38-4ea5-8006-c3fe5f74946e"),
                            Location = "Delhi",
                            Name = "Vishesh Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("26d44697-7fe3-454e-adbf-8b3242627e5d"),
                            Location = "Pune",
                            Name = "Amit Sharma"
                        },
                        new
                        {
                            Id = new Guid("f9f6bc6c-89be-4384-8e86-335edc89c1b9"),
                            Location = "Gandhinagar",
                            Name = "Vishesh Virani"
                        },
                        new
                        {
                            Id = new Guid("7bcc009e-0fa0-4fbb-b890-d2e0e1650242"),
                            Location = "Bangalore",
                            Name = "Amit Virani"
                        },
                        new
                        {
                            Id = new Guid("91887dde-7975-4c0b-8420-cc6987b08529"),
                            Location = "Chennai",
                            Name = "Harsh Sharma"
                        },
                        new
                        {
                            Id = new Guid("a191afc3-fe45-4af8-9d9f-298e016cc197"),
                            Location = "Ahmedabad",
                            Name = "Darshil Rathod"
                        },
                        new
                        {
                            Id = new Guid("ed104c5b-201f-4f40-b486-3d679cfe4c9b"),
                            Location = "Pune",
                            Name = "Harsh Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("885918c3-8504-4b7c-9715-96597d32263e"),
                            Location = "Pune",
                            Name = "Naisarg Sharma"
                        },
                        new
                        {
                            Id = new Guid("e94a00e6-080b-43ff-ae1e-91762f8df0d7"),
                            Location = "Pune",
                            Name = "Raj Agrawal"
                        },
                        new
                        {
                            Id = new Guid("013cd00b-8c02-4f14-8222-f30ae0787579"),
                            Location = "Ahmedabad",
                            Name = "Raj Verma"
                        },
                        new
                        {
                            Id = new Guid("54acb281-3cf3-4add-a86a-ae33e4787b4c"),
                            Location = "Bangalore",
                            Name = "Ramesh Sharma"
                        });
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.DeliveryBoy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryBoys");
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.MarketPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MarketPlaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41a8ed9f-8033-4a8b-b777-70f33a253c5e"),
                            Name = "Zomato"
                        },
                        new
                        {
                            Id = new Guid("70c6ccc4-9fb9-4b77-b7cd-0d3b541d1438"),
                            Name = "Swiggy"
                        },
                        new
                        {
                            Id = new Guid("8f4ed288-7a20-4855-8786-ecef5ca111e4"),
                            Name = "Uber Eats"
                        },
                        new
                        {
                            Id = new Guid("11ddaa28-d601-46bd-967d-6475aa06c329"),
                            Name = "Food Panda"
                        });
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.Orders", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutletName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBill")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.Outlet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<Guid>("RestaurantId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId1");

                    b.ToTable("Outlets");
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0520728-f5d1-477f-afeb-3dc2de3f3b03"),
                            Name = "KFC"
                        },
                        new
                        {
                            Id = new Guid("f87e3ef4-a1bd-413a-8bc7-67b3a207cf37"),
                            Name = "Dominos"
                        },
                        new
                        {
                            Id = new Guid("255f3953-dd20-484d-a2b4-34fe9635294c"),
                            Name = "Pizza Hut"
                        },
                        new
                        {
                            Id = new Guid("183b49eb-9e49-42fd-8b48-f010d8202c4b"),
                            Name = "City Point"
                        },
                        new
                        {
                            Id = new Guid("b24030f0-7a8e-45fa-8faf-45fdf9265852"),
                            Name = "Farki "
                        });
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.Outlet", b =>
                {
                    b.HasOne("MarketPlace_Orders.Models.Restaurant", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurant");
                });
#pragma warning restore 612, 618
        }
    }
}
