// <auto-generated />
using System;
using MarketPlace_Orders.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketPlace_Orders.Migrations
{
    [DbContext(typeof(MarketPlaceContext))]
    [Migration("20220912173226_SeedingData")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.7.22376.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarketPlace_Orders.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5caac370-3076-46c9-a8c5-11204374767c"),
                            Location = "Goa",
                            Name = "Kush Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("5a228307-1423-4799-8a7b-7496b36b3dbc"),
                            Location = "Ahmedabad",
                            Name = "Darshil Parmar"
                        },
                        new
                        {
                            Id = new Guid("dfd3a378-fc1e-4906-84ff-53e8970a8e66"),
                            Location = "Pune",
                            Name = "Vishesh Agrawal"
                        },
                        new
                        {
                            Id = new Guid("b82057df-15b2-4890-b1d1-b3c49900795a"),
                            Location = "Mumbai",
                            Name = "Darshil Maheriya"
                        },
                        new
                        {
                            Id = new Guid("f2229249-f6a5-43be-8bd8-f3d9f5b453f6"),
                            Location = "Ahmedabad",
                            Name = "Tejas Parmar"
                        },
                        new
                        {
                            Id = new Guid("ee6f1c93-9355-420d-8581-cc0038ce931a"),
                            Location = "Gandhinagar",
                            Name = "Kush Virani"
                        },
                        new
                        {
                            Id = new Guid("f3bb20c8-270f-4211-b0e2-0ecfd800e22f"),
                            Location = "Mumbai",
                            Name = "Darshil Agrawal"
                        },
                        new
                        {
                            Id = new Guid("245d8ef9-c58f-4f31-b8d9-a7f7adcd52d0"),
                            Location = "Goa",
                            Name = "Aelish Parmar"
                        },
                        new
                        {
                            Id = new Guid("fca5e0e7-74d7-49da-9486-2df095e62f7e"),
                            Location = "Mumbai",
                            Name = "Darshil Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("20fadabb-a56d-4f6d-bd7c-deacaa68d24e"),
                            Location = "Delhi",
                            Name = "Harsh Virani"
                        },
                        new
                        {
                            Id = new Guid("142a6a38-66ae-4147-a973-55c699192d20"),
                            Location = "Goa",
                            Name = "Kush Maheriya"
                        },
                        new
                        {
                            Id = new Guid("4b5dfd65-3825-4158-a46b-450e31b86dd1"),
                            Location = "Gandhinagar",
                            Name = "Vishesh Virani"
                        },
                        new
                        {
                            Id = new Guid("c9bf0bbb-cf23-4cb1-929f-d119c4557199"),
                            Location = "Ahmedabad",
                            Name = "Tejas Virani"
                        },
                        new
                        {
                            Id = new Guid("9c62c733-1503-48b7-a8b9-567aa6248b59"),
                            Location = "Kolkata",
                            Name = "Vishesh Parmar"
                        },
                        new
                        {
                            Id = new Guid("70e2f66e-d733-4064-9b45-84d7ee8d7dfb"),
                            Location = "Delhi",
                            Name = "Darshil Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("58af47e7-138c-423c-8a70-e90fe5dcd3e9"),
                            Location = "Bangalore",
                            Name = "Tejas Virani"
                        },
                        new
                        {
                            Id = new Guid("9c032636-0e2b-4949-b658-a9deb3e0ded4"),
                            Location = "Bangalore",
                            Name = "Kush Maheriya"
                        },
                        new
                        {
                            Id = new Guid("16e35e8c-34f6-49fe-9c7c-3c44e7628a9d"),
                            Location = "Goa",
                            Name = "Kush Agrawal"
                        },
                        new
                        {
                            Id = new Guid("1797151e-8455-48fe-b6fb-8688fba17ac9"),
                            Location = "Kolkata",
                            Name = "Kush Agrawal"
                        },
                        new
                        {
                            Id = new Guid("3689222d-34aa-4dbe-8b10-c264312a5d4a"),
                            Location = "Delhi",
                            Name = "Aelish Maheriya"
                        },
                        new
                        {
                            Id = new Guid("b88fdd18-3987-448b-bf88-380a39117c9d"),
                            Location = "Kerala",
                            Name = "Vishesh Virani"
                        },
                        new
                        {
                            Id = new Guid("879cfa99-27a9-474f-a8f3-3210d57b4fae"),
                            Location = "Gandhinagar",
                            Name = "Kush Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("fd1000b5-49d3-489a-98f9-efcc95e73d30"),
                            Location = "Goa",
                            Name = "Aelish Parmar"
                        },
                        new
                        {
                            Id = new Guid("4646fff4-84fa-48b2-a8b7-c2437123b4d9"),
                            Location = "Goa",
                            Name = "Harsh Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("70c7f0b8-2b9d-4e2a-9e33-8f9a10c51ca4"),
                            Location = "Kerala",
                            Name = "Kush Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("db13889f-0779-4d48-b358-588e0da4aea9"),
                            Location = "Chennai",
                            Name = "Vishesh Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("a7d95d63-494f-4c32-9fb2-e3653c203a0a"),
                            Location = "Goa",
                            Name = "Kush Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("ac21e032-3a6b-4d7d-93f8-5116526dc6bb"),
                            Location = "Delhi",
                            Name = "Aelish Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("6b72780c-d2b6-44ef-a2ad-6ad5c95cd026"),
                            Location = "Kerala",
                            Name = "Kush Virani"
                        },
                        new
                        {
                            Id = new Guid("ca22d54c-106d-4f38-a66d-0b88ade42847"),
                            Location = "Ahmedabad",
                            Name = "Tejas Parmar"
                        },
                        new
                        {
                            Id = new Guid("98fa7b88-b7b5-47ae-b13d-5393310fdc31"),
                            Location = "Bangalore",
                            Name = "Tejas Parmar"
                        },
                        new
                        {
                            Id = new Guid("4c600b6c-3dc0-4f5a-88eb-e3983f6fc3d4"),
                            Location = "Ahmedabad",
                            Name = "Kush Virani"
                        },
                        new
                        {
                            Id = new Guid("9106984a-176b-47ce-b51a-27eca0d4578e"),
                            Location = "Mumbai",
                            Name = "Darshil Parmar"
                        },
                        new
                        {
                            Id = new Guid("f72b0c42-b93f-48b3-9da9-9c4479aa3df6"),
                            Location = "Goa",
                            Name = "Tejas Agrawal"
                        },
                        new
                        {
                            Id = new Guid("a1970ab0-b9ff-4e58-9973-390e6bf9f25f"),
                            Location = "Mumbai",
                            Name = "Darshil Parmar"
                        },
                        new
                        {
                            Id = new Guid("f93041c5-b2b6-4e74-93e8-b04fdc462fac"),
                            Location = "Kolkata",
                            Name = "Kush Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("6ea5fed2-7667-4f0f-af05-19ad3aee1a48"),
                            Location = "Pune",
                            Name = "Aelish Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("d9bf8027-023f-437f-9546-c8bc307a5bbd"),
                            Location = "Ahmedabad",
                            Name = "Tejas Vaghasiya"
                        },
                        new
                        {
                            Id = new Guid("7ba1989c-cb1f-4244-a461-eca161d329af"),
                            Location = "Mumbai",
                            Name = "Vishesh Maheriya"
                        },
                        new
                        {
                            Id = new Guid("02102dd6-e848-4498-9269-a58a95ad4cf7"),
                            Location = "Ahmedabad",
                            Name = "Harsh Parmar"
                        },
                        new
                        {
                            Id = new Guid("88d397f0-d50d-4d22-ab33-157fd85fab9a"),
                            Location = "Kolkata",
                            Name = "Aelish Virani"
                        },
                        new
                        {
                            Id = new Guid("8b0dfba1-3fa2-4fb5-b2f5-2f6366bb1cbf"),
                            Location = "Goa",
                            Name = "Kush Agrawal"
                        },
                        new
                        {
                            Id = new Guid("d9bd88be-139e-4a18-8a2c-c77075dcaa1d"),
                            Location = "Goa",
                            Name = "Harsh Agrawal"
                        },
                        new
                        {
                            Id = new Guid("2b6997c6-eda4-4d80-bc5f-001191133dc9"),
                            Location = "Goa",
                            Name = "Kush Agrawal"
                        },
                        new
                        {
                            Id = new Guid("185175a6-c32e-4616-a3f5-9308eb77d19a"),
                            Location = "Delhi",
                            Name = "Vishesh Parmar"
                        },
                        new
                        {
                            Id = new Guid("8b5ac082-480b-4657-a851-8909369e9e24"),
                            Location = "Goa",
                            Name = "Aelish Virani"
                        },
                        new
                        {
                            Id = new Guid("c4897847-c775-4398-ac9d-88cad316ea94"),
                            Location = "Delhi",
                            Name = "Aelish Maheriya"
                        },
                        new
                        {
                            Id = new Guid("68e4495c-e422-4052-97b0-3bf66794ef19"),
                            Location = "Goa",
                            Name = "Kush Parmar"
                        },
                        new
                        {
                            Id = new Guid("fb93d0a1-7d8f-4170-aebf-532084cd865a"),
                            Location = "Kolkata",
                            Name = "Harsh Kanzariya"
                        },
                        new
                        {
                            Id = new Guid("b11eec19-b010-48b8-827a-b4b418ceb080"),
                            Location = "Delhi",
                            Name = "Vishesh Kanzariya"
                        });
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.DeliveryBoy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryBoys");
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.MarketPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MarketPlaces");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b3f9a44-1738-44c2-a984-a1d308e386bc"),
                            Name = "Zomato"
                        },
                        new
                        {
                            Id = new Guid("566e646a-495c-4cdc-839b-4fb391a85c41"),
                            Name = "Swiggy"
                        },
                        new
                        {
                            Id = new Guid("daa81a82-e2fe-4d00-8465-56dcf75108fd"),
                            Name = "Uber Eats"
                        },
                        new
                        {
                            Id = new Guid("e97037d4-2b66-4637-b174-dd95f2f4251b"),
                            Name = "Food Panda"
                        });
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.Orders", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OutletName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RestaurantName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalBill")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<Guid>("RestaurantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.Restaurant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5317717e-63e1-4cc3-8e56-a2687a26bbd1"),
                            Name = "KFC"
                        },
                        new
                        {
                            Id = new Guid("bc3579e0-5611-4700-a540-a8521f8adf42"),
                            Name = "Dominos"
                        },
                        new
                        {
                            Id = new Guid("14bebdfd-78f3-49d5-aa00-30bbbe95a62e"),
                            Name = "Pizza Hut"
                        },
                        new
                        {
                            Id = new Guid("f736355c-3d23-4cee-867c-64befa46e189"),
                            Name = "City Point"
                        },
                        new
                        {
                            Id = new Guid("2a8b3afc-771a-4fc8-a93b-8b91226d9207"),
                            Name = "Farki "
                        });
                });

            modelBuilder.Entity("MarketPlace_Orders.Models.Product", b =>
                {
                    b.HasOne("MarketPlace_Orders.Models.Restaurant", "Rest")
                        .WithMany()
                        .HasForeignKey("RestaurantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rest");
                });
#pragma warning restore 612, 618
        }
    }
}
